### ISSUE TITLE
Seeing spikes to 32,000 CPM

### ISSUE THREAD

**Issue by krbaker** [climateguard/RadSens#10]
I fairly often see spikes to 32,000 CPM.  I'm guessing this is a math issue with either a counter wrapping or unsigned value going negative.  I will dig more but just flagging this in case it's obvious to anyone already in the code.  Great work.

Normally seeing around 30cpm

**Comment by bakerkj** [comment]
I am seeing something very similar. Jumping to 32,016.

**Comment by bakerkj** [comment]
I wonder if this is a related or the same issue here https://github.com/maaad/RadSens1v2/issues/3

**Comment by maaad** [comment]
Try this https://github.com/maaad/RadSens1v2/issues/3#issuecomment-1289578773 as a workaround for spikes with 1v5

**Comment by octopolyr** [comment]
Hi!
We've recieved some same issues, but trouble not on our side. I'll close the issue with merging the pull request in 1-2 days
@krbaker @bakerkj
