### ISSUE TITLE
Wrong dimension in datasheet

### ISSUE THREAD

**Issue by tcottle** [climateguard/RadSens#12]
The datasheet shows the PCB as 88mm wide.  The correct dimension is 120mm in the 1V5 PCB
![1](https://user-images.githubusercontent.com/3618531/206599941-4a88c434-3c85-4db6-b91c-e3baf7dfa7c3.png)

**Comment by climateguard** [comment]
Hello, you mean Radsens long version. We added info but not in all datasheets. We will add drawing for it in english datasheet version soon. Thank you for showing the issue.   Radsens long version has 120mm length and short version 88 mm
![image](https://user-images.githubusercontent.com/48715336/209684181-014ffe9e-3da2-4fd1-a579-903760842875.png)
