### ISSUE TITLE
getNumberOfPulses() always increasing number...

### ISSUE THREAD

**Issue by earlthesquirrel** [climateguard/RadSens#15]
The comment in the code says:

`Returns the accumulated number of pulses registered by the module since the last I2C data reading`

But in practice, running the test code, it is an ever increasing number.  Is there some way to cause it to reset?

**Comment by climateguard** [comment]
Good afternoon, yes, library use _pulscnt to store pulses. You can get current pulses. You need to change method update_pulses() and change getNumberOfPulses() inside the cpp file to return the current i2c values. Is it will be a problem for you?

**Comment by earlthesquirrel** [comment]
Yeah, I can make those additions.   Thanks for the description... I looked at the code and see what needs to change...
