### ISSUE TITLE
Issue with setSensitivity function

### ISSUE THREAD

**Issue by RajeshAcpl** [climateguard/RadSens#3]
Hi,

I am unable to change the Pav coefficient using the setSensitivity function call. Given below is the output of the unmodified I2C_rad_test.ino example program:

03:38:48.923 -> Chip id: 0x7D
03:38:48.957 -> Firmware version: 2
03:38:48.957 -> -------------------------------------
03:38:48.957 -> Set Sensitivity example:
03:38:48.957 -> 
03:38:48.957 -> 	 getSensitivity(): 105
03:38:48.957 -> 	 setSensitivity(55)... 
03:38:48.992 -> 	 getSensitivity(): 0
03:38:48.992 -> 	 setSensitivity(105)... 
03:38:48.992 -> 	 getSensitivity(): 0
03:38:49.060 -> 
03:38:49.060 -> 	 HV generator state: 0
03:38:49.060 -> 	 setHVGeneratorState(false)... 
03:38:49.060 -> 	 HV generator state: 0
03:38:49.060 -> 	 setHVGeneratorState(true)... 
03:38:49.060 -> 	 HV generator state: 1
03:38:49.060 -> -------------------------------------
03:38:49.060 -> Rad intensy dyanmic: 21.30
03:38:49.060 -> Rad intensy static: 17.40
03:38:49.060 -> Number of pulses: 2
03:38:51.052 -> Rad intensy dyanmic: 22.00
03:38:51.052 -> Rad intensy static: 18.40

I am using Arduino version 1.8.16 and RadSens 1v5

-Rajesh

**Comment by climateguard** [comment]
thanks, we have update the lib, please check
